version: '3.9'
name: 'session-service'
services:

  redis:
    image: redis
    ports:
      - "6379:6379"
  
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: "local:redis:6379"  
    command: []

  session-http:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    env_file:
      - .env
    environment:
      SERVER_TYPE: http
    depends_on:
      - redis

  session-grpc:
    build:
      dockerfile: Dockerfile
    ports:
      - "3010:8080"
    env_file:
      - .env
    environment:
      SERVER_TYPE: grpc
    depends_on:
      - redis